//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaniTerapija
    {
        public int DanID { get; set; }
        public Nullable<int> PretragaID { get; set; }
        public Nullable<int> Datum { get; set; }
        public string Dan { get; set; }
        public Nullable<bool> Terapija { get; set; }
    }
}
