//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IskazniceDopunsko
    {
        public int DopunskoID { get; set; }
        public string Broj { get; set; }
        public Nullable<int> NeVrijediOd { get; set; }
    }
}
