//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategorijeOsiguranja
    {
        public int KategorijeID { get; set; }
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public string Napomena { get; set; }
    }
}
