//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijecnici
    {
        public int LijecnikID { get; set; }
        public string Sifra { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Titula { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> MjestoID { get; set; }
        public string Telefon { get; set; }
        public string Gsm { get; set; }
        public string EMail { get; set; }
        public Nullable<int> SpolID { get; set; }
        public string Jmbg { get; set; }
        public string MaticniBroj { get; set; }
        public string Funkcija { get; set; }
        public Nullable<bool> Neaktivan { get; set; }
        public Nullable<bool> NijeLijecnik { get; set; }
        public string CezihKartica { get; set; }
        public byte[] CezihLicenca { get; set; }
        public string HCProviderUniqueIdentifier { get; set; }
        public string InstanceIdentifier { get; set; }
        public string HCOrganizationInstanceIdentifier { get; set; }
        public Nullable<int> SobaID { get; set; }
        public Nullable<bool> HrDijagnoze { get; set; }
        public string TitulaPrefiks { get; set; }
        public string LijecnikPrikaz { get; set; }
        public Nullable<bool> Ispis { get; set; }
        public string Specijalnost { get; set; }
        public Nullable<int> ProfitniCentarID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public Nullable<bool> OdabirRacuni { get; set; }
        public Nullable<bool> SobaPoDanu { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> OldID { get; set; }
        public Nullable<int> TipHzzoID { get; set; }
    }
}
