//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mjesta
    {
        public int MjestoID { get; set; }
        public string Posta { get; set; }
        public string Mjesto { get; set; }
        public Nullable<int> ZupanijaID { get; set; }
        public Nullable<int> DrzavaID { get; set; }
        public Nullable<bool> GradPostupakNeDodatno { get; set; }
        public Nullable<int> GradPostupakNeDodatnoOd { get; set; }
    }
}
