//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacijenti
    {
        public int PacijentID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> MaticniBroj { get; set; }
        public Nullable<int> SpolID { get; set; }
        public Nullable<int> DatumRodjenja { get; set; }
        public string Tezina { get; set; }
        public string Jmbg { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Gsm { get; set; }
        public string EMail { get; set; }
        public Nullable<int> MjestoID { get; set; }
        public string Napomena { get; set; }
        public bool Aktivni { get; set; }
        public bool UObradi { get; set; }
        public Nullable<int> HzzoID { get; set; }
        public Nullable<int> KategorijaOsiguranjaID { get; set; }
        public string ZdrastvenaIskaznica { get; set; }
        public string DopunskoOsiguranje { get; set; }
        public string StomatoloskoPomagalo { get; set; }
        public string Karton { get; set; }
        public string BolesnickiList { get; set; }
        public string BrojPutovnice { get; set; }
        public string BrojOsiguranjaIno { get; set; }
        public bool Sudjelovanje { get; set; }
        public Nullable<int> SudjelovanjeID { get; set; }
        public Nullable<int> OslobadanjeID { get; set; }
        public Nullable<int> IskaznicaID { get; set; }
        public string UputniLijecnik { get; set; }
        public string SerijskiBrojUputnice { get; set; }
        public string BracnoStanje { get; set; }
        public string Obitelj { get; set; }
        public string Zaposlenje { get; set; }
        public string Poslodavac { get; set; }
        public string Zvanje { get; set; }
        public string OsobniLijecnik { get; set; }
        public string KrvnaGrupa { get; set; }
        public string RhFaktor { get; set; }
        public Nullable<int> GodinaRodjenja { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> C_DateCreated { get; set; }
        public Nullable<System.DateTime> C_DateModified { get; set; }
        public string Visina { get; set; }
        public string Alergija { get; set; }
        public string Dijagnoza { get; set; }
        public Nullable<int> PrvaHD { get; set; }
        public string PrvaHDNapomena { get; set; }
        public string MarkeriBHep { get; set; }
        public string MarkeriCHep { get; set; }
        public Nullable<int> MjestpPHDID { get; set; }
        public Nullable<int> MjestoTipID { get; set; }
        public Nullable<int> DopOsigVrijediDo { get; set; }
        public Nullable<bool> DodatnoDopOsig { get; set; }
        public string Oib { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> UserModID { get; set; }
        public Nullable<int> HL7ID { get; set; }
        public Nullable<int> TipID { get; set; }
        public Nullable<bool> PreporukaPostojeceg { get; set; }
        public Nullable<int> NacinDolaskaID { get; set; }
        public Nullable<int> PacijentPreporukaID { get; set; }
        public Nullable<int> PreostaloTerapija { get; set; }
        public Nullable<int> DopunskoID { get; set; }
        public string InozemniBroj { get; set; }
        public string InozemniBrojOznaka { get; set; }
        public Nullable<bool> Preuzmi { get; set; }
        public string UputnaUstanova { get; set; }
        public Nullable<bool> StudijaOfta { get; set; }
        public Nullable<int> OznakaUpucivanjaPacID { get; set; }
        public Nullable<int> DatumUpucivanjaPac { get; set; }
        public Nullable<int> TipNalazaID { get; set; }
        public string JINPac { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> OldID { get; set; }
        public string ImeOcaMajke { get; set; }
        public Nullable<int> MjestoRodjenjaID { get; set; }
        public Nullable<bool> NalazXml { get; set; }
        public Nullable<bool> DatotekaPreuzimanje { get; set; }
        public Nullable<bool> EMailNo { get; set; }
        public Nullable<int> EMailDatum { get; set; }
    }
}
