//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partneri
    {
        public int PartnerID { get; set; }
        public string SifraPartnera { get; set; }
        public string Partner { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> MjestoID { get; set; }
        public Nullable<bool> Bolnica { get; set; }
        public string MaticniBroj { get; set; }
        public Nullable<int> BrojDanaOdgode { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> C_DateCreated { get; set; }
        public Nullable<System.DateTime> C_DateModified { get; set; }
        public string Oib { get; set; }
        public string PozivNaBroj { get; set; }
        public string ZiroRacun { get; set; }
        public Nullable<bool> FizickaOsoba { get; set; }
        public string InozemniBroj { get; set; }
        public string InozemniBrojOznaka { get; set; }
        public string Adresa2 { get; set; }
        public Nullable<int> Mjesto2ID { get; set; }
        public Nullable<bool> Adresa1Ispis { get; set; }
        public Nullable<bool> Adresa2Ispis { get; set; }
        public string FreeInfoRacun { get; set; }
        public string FreeInfoRacunEng { get; set; }
        public Nullable<int> TipID { get; set; }
        public Nullable<float> PopustRad { get; set; }
        public Nullable<float> PopustMaterijal { get; set; }
        public Nullable<float> PopustRadPrijevremeno { get; set; }
        public Nullable<float> PopustMaterijalPrijevremeno { get; set; }
        public Nullable<bool> IspisPartnera { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> OldID { get; set; }
    }
}
