//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sobe
    {
        public int SobaID { get; set; }
        public string Soba { get; set; }
        public string Opis { get; set; }
        public bool Aktivna { get; set; }
        public string ForeColor { get; set; }
        public string BackColor { get; set; }
        public string Caption { get; set; }
        public string Ikona { get; set; }
        public Nullable<int> BrojPretrage { get; set; }
        public Nullable<int> BrojNalaza { get; set; }
        public Nullable<int> Redoslijed { get; set; }
        public string BackColorActive { get; set; }
        public string BackColorUputnica { get; set; }
        public Nullable<int> DjelatnostID { get; set; }
        public string OznakaSobe { get; set; }
        public string MjestoIspisaSobe { get; set; }
        public Nullable<bool> Hl7 { get; set; }
        public string HL7Aplikacija { get; set; }
        public string IspisSestrinskogNalaza { get; set; }
        public string IspisSestrinskogNalazaMemo { get; set; }
        public Nullable<bool> IspisTermina { get; set; }
        public string Napomena { get; set; }
        public string ENarNazivRadilista { get; set; }
        public string ENarAdresa { get; set; }
        public string ENarSifraHzzo { get; set; }
        public Nullable<bool> ENarNemaTermina { get; set; }
        public Nullable<int> ENarNemaTerminaID { get; set; }
        public string ENarNemaTerminaRazlog { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> OldID { get; set; }
        public Nullable<int> Hl7RadilisteID { get; set; }
    }
}
