//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPermissions
    {
        public int Broj { get; set; }
        public int UserID { get; set; }
        public int ModuleID { get; set; }
        public int AccountID { get; set; }
        public Nullable<bool> Pokreni { get; set; }
        public Nullable<bool> CanShow { get; set; }
        public Nullable<bool> CanAdd { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanSave { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanPrint { get; set; }
        public Nullable<bool> CanPreview { get; set; }
        public Nullable<bool> CanRun { get; set; }
        public Nullable<bool> CanFinalize { get; set; }
        public Nullable<bool> CanStorno { get; set; }
        public Nullable<bool> CanSeeOthers { get; set; }
        public Nullable<bool> CanChangeOthers { get; set; }
        public Nullable<bool> CanSaveOthers { get; set; }
        public Nullable<bool> CanPrintOthers { get; set; }
    }
}
