//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedisysEntities : DbContext
    {
        public MedisysEntities()
            : base("name=MedisysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersCurrent> UsersCurrent { get; set; }
        public virtual DbSet<UsersLog> UsersLog { get; set; }
        public virtual DbSet<UsersPermissions> UsersPermissions { get; set; }
    }
}
