//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zupanije
    {
        public int ZupanijaID { get; set; }
        public string Oznaka { get; set; }
        public string Zupanija { get; set; }
        public string Predbroj { get; set; }
        public string Napomena { get; set; }
        public Nullable<int> C_KorisnikID { get; set; }
        public Nullable<System.DateTime> C_Created { get; set; }
        public Nullable<System.DateTime> C_Modified { get; set; }
        public bool C_Deleted { get; set; }
    }
}
